export const STATES = [
    { id: 1, label: 'Aguascalientes' },
    { id: 2, label: 'Baja California' },
    { id: 3, label: 'Baja California Sur' },
    { id: 4, label: 'Campeche' },
    { id: 5, label: 'Chiapas' },
    { id: 6, label: 'Chihuahua' },
    { id: 7, label: 'Coahuila de Zaragoza' },
    { id: 8, label: 'Colima' },
    { id: 9, label: 'Ciudad de México' },
    { id: 10, label: 'Durango' },
    { id: 11, label: 'Guanajuato' },
    { id: 12, label: 'Guerrero' },
    { id: 13, label: 'Hidalgo', },
    { id: 14, label: 'Jalisco' },
    { id: 15, label: 'Estado de Mexico' },
    { id: 16, label: 'Michoacan de Ocampo' },
    { id: 17, label: 'Morelos' },
    { id: 18, label: 'Nayarit' },
    { id: 19, label: 'Nuevo Leon' },
    { id: 20, label: 'Oaxaca' },
    { id: 21, label: 'Puebla' },
    { id: 22, label: 'Queretaro de Arteaga' },
    { id: 23, label: 'Quintana Roo' },
    { id: 24, label: 'San Luis Potosi' },
    { id: 25, label: 'Sinaloa' },
    { id: 26, label: 'Sonora' },
    { id: 27, label: 'Tabasco' },
    { id: 28, label: 'Tamaulipas' },
    { id: 29, label: 'Tlaxcala' },
    { id: 30, label: 'Veracruz de Ignacio de la Llave' },
    { id: 31, label: 'Yucatan' },
    { id: 32, label: 'Zacatecas' },
];